# Generated by Django 3.0.4 on 2020-03-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
