# Generated by Django 3.0.4 on 2020-03-10 13:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_patient'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='patient',
            managers=[
                ('value', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_id',
            new_name='did',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_bg',
            new_name='bg',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='pid',
        ),
    ]
